data <- read.csv("obese1.csv")
summary(data)
model <- lm(data$obese ~ data$sex + data$sbp + data$dbp + data$scl + data$age + data$bmi)
plot(data)
summary(model)
resid(model)
fitted(model)
par(mfrow = c(2,2))
plot(model)
model <- lm(data$obese ~ data$sbp + data$dbp)
summary(model)
plot(model)